volumes:
  postgres-data:

services:
  app:
    container_name: ambiente-dev
    build: .
    environment:
        POSTGRES_PASSWORD: postgres
        POSTGRES_USER: postgres
        POSTGRES_DB: postgres
        POSTGRES_HOSTNAME: localhost
    volumes:
      -  .:/home/toolbox/workspace:cached
    tty: true
  db:
    container_name: postgresdb
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    network_mode: service:app
  mail:
    container_name: smtp4dev
    image: rnwood/smtp4dev
    network_mode: service:app
    environment:
      - SERVEROPTIONS__URLS=http://*:2525
      - ASPNETCORE_HTTP_PORTS=2525